quantize: # quantize param
  quantize_pose_quaternion_bit_width : 8
  quantize_pose_quaternion_il : 1
  quantize_pose_transition_bit_width : 8
  quantize_pose_transition_il : 3

  quantize_imu_speed_bit_width : 8
  quantize_imu_speed_il : 2
  quantize_imu_accbias_bit_width : 8
  quantize_imu_accbias_il : 2
  quantize_imu_gyrobias_bit_width : 8
  quantize_imu_gyrobias_il : 2

  quantize_inverse_depth_bit_width : 16
  quantize_inverse_depth_il : 7

  quantize_hessian_bit_width : 64
  quantize_hessian_il : 32
  quantize_b_bit_width : 64
  quantize_b_il : 32

flag: # gxt flag
  use_gxt_backend: true
  enable_quantize: true
